apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "filebeat.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "filebeat.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "filebeat.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "filebeat.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "filebeat.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: filebeat-config
              mountPath: /usr/share/filebeat/filebeat.yml
              subPath: filebeat.yml
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
      volumes:
        - name: filebeat-config
          configMap:
            defaultMode: 420
            name: {{ include "filebeat.fullname" . }}
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
