filebeat.inputs:
  # - type: log
    # paths:
      # - "/var/lib/docker/containers/*/*.log"
    # processors:
      # - add_kubernetes_metadata:
          # in_cluster: true
      # - decode_json_fields:
          # fields: ["log"]
          # target: ""

    # json.message_key: log
    # json.keys_under_root: true
    # json.add_error_key: true

    # multiline.pattern: '^[\d]{4}-[\d]{2}-[\d]{2}\s[\d]{2}:[\d]{2}:[\d]{2}.[\d]{3}\s{1,2}[A-Z]{4,5}\s|^{".?timestamp":'
    # multiline.match: after
    # multiline.negate: true

    # close_inactive: 5m

  - type: docker
    containers.ids: "*"
    containers.path: "/var/lib/docker/containers"
    combine.parial: true
    processors:
      - add_kubernetes_metadata:
          in_cluster: true

    close_inactive: 5m

output.logstash:
    hosts: ["logstash:5044"]
