filebeat.prospectors:
  - type: log
    paths:
     - '/var/lib/docker/containers/*/*.log'
    processors:
      - add_kubernetes_metadata:
          in_cluster: true
          fields: ['log']
          target: ""
      - decode_json_fields:

    close_inactive: 5m

output.logstash:
  hosts: ["logstash:5044"]
