apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "elasticsearch.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
data:
 elasticsearch.yml: |
  cluster.name: {{ .Values.configuration.clusterName }}
  discovery.type: single-node
  network.host: "0.0.0.0"
