{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "elasticsearch.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - http:
        paths:
          - path: /elasticsearch
            backend:
              serviceName: {{ include "elasticsearch.fullname" . }}
              servicePort: {{ .Values.service.port  }}
{{- end }}
