input {
  beats {
    port => 5044
  }
}

filter {
  grok {
    match => { "message" => "%{WORD:someword} %{WORD:somenum}" }
  }
}

output {
  if [kubernetes][namespace] == "monitoring"
  or [kubernetes][namespace] == "kube-system" {
    elasticsearch {
      hosts => ["elasticsearch:9200"]
      index => "infrastructure-%{+YYYY.MM.dd}"
    }
  }
  else {
    elasticsearch {
      hosts => ["elasticsearch:9200"]
      index => "else-logs-%{+YYYY.MM.dd}"
    }
  }
}
