input {
  file {
    path => "/var/log/example/*.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    add_field => { "[@metadata][source_type]" => "file" }
  }

  beats {
    port => 5044
    add_field => { "[@metadata][source_type]" => "beats" }
  }
}

filter {
  grok {
    match => { "message" => "%{WORD:someword} %{WORD:somenum}" }
  }

  # date {
    # match => [ "timestamp", "dd/MMM/yyyy:HH:mm:ss Z" ]
  # }
}

output {
  if [@metadata][source_type] == "file" {
    elasticsearch {
      hosts => ["elasticsearch:9200"]
      index => "logstash-from-file-%{+YYYY.MM.dd}"
    }
  }
  else if [@metadata][source_type] == "beats" {
    elasticsearch {
      hosts => ["elasticsearch:9200"]
      index => "logstash-from-beats-%{+YYYY.MM.dd}"
    }
  }
}
