input {
  beats {
    port => 5044
  }
}

filter {
  grok {
    match => { "log" => "^%{TIMESTAMP_ISO8601:service_time}\s*%{LOGLEVEL:level}" }
  }

  if [kubernetes][namespace] == "web" and ![kubernetes][labels][app][kubernetes] {
    mutate {
      rename => { "[kubernetes][labels][app]" => "[kubernetes][labels][app][kubernetes][io/name]" }
    }
  }
}

output {
  if [kubernetes][namespace] == "monitoring"
  or [kubernetes][namespace] == "kube-system" {
    elasticsearch {
      hosts => ["elasticsearch:9200"]
      index => "infrastructure-%{+YYYY.MM.dd}"
    }
  }
  if [kubernetes][namespace] == "web" {
    elasticsearch {
      hosts => ["elasticsearch:9200"]
      index => "web-%{+YYYY.MM.dd}"
    }
  }
  else {
    elasticsearch {
      hosts => ["elasticsearch:9200"]
      index => "else-logs-%{+YYYY.MM.dd}"
    }
  }
}
