apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kibana.fullname" . }}
  labels:
    {{- include "kibana.labels" . | nindent 4 }}
data:
 kibana.yml: |
    server.name: kibana
    server.port: 5601
    server.host: "0"
    elasticsearch.hosts: "http://elasticsearch:9200"
    xpack.monitoring.ui.container.elasticsearch.enabled: true
