{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "kibana.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kibana.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - path: /kibana(/|$)(.*)
            backend:
              serviceName: {{ include "kibana.fullname" . }}
              servicePort: {{ .Values.service.port  }}
{{- end }}
