version: '3'
services:

  elasticsearch:
    image: elasticsearch:7.6.0
    container_name: elasticsearch
    environment:
      - cluster.name=elk-cluster-sandbox
      - discovery.type=single-node
    ports:
      - 9200:9200
    networks:
      - elk-cluster-sandbox

  kibana:
    image: kibana:7.6.0
    container_name: kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - elk-cluster-sandbox
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/logstash.yml:ro

  logstash:
    image: logstash:7.6.0
    container_name: logstash
    ports:
      - 5044:5044
    depends_on:
      - elasticsearch
    networks:
      - elk-cluster-sandbox
    volumes:
      - ./logstash/:/usr/share/logstash/pipeline/:ro
      - ./example-logs/grok-logs/:/var/log/example/

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.6.0
    entrypoint: "filebeat -e -strict.perms=false" # to be able to add config
    container_name: filebeat
    user: root
    depends_on:
      - logstash
      - elasticsearch
    networks:
      - elk-cluster-sandbox
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./example-logs/json-logs/:/var/log/example/

networks:
  elk-cluster-sandbox:
