# Default values for kibana.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: docker.elastic.co/kibana/kibana
  pullPolicy: IfNotPresent

namespace: monitoring

service:
  type: ClusterIP
  port: 5601

ingress:
  enabled: true

resources: {}
