apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "logstash.fullname" . }}-example-logs"
  labels:
    {{- include "logstash.labels" . | nindent 4 }}
data:
  example-logs.log: |-
{{ .Files.Get "app-data/example-logs.log" | indent 4 }}
