apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "logstash.fullname" . }}
  labels:
    {{- include "logstash.labels" . | nindent 4 }}
data:
  logstash.yml: |-
{{ .Files.Get "app-data/logstash.yml" | indent 4 }}
